name: unischedule
description: "Efficient time management and meeting coordination."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  flutter_riverpod: ^2.5.1
  local_auth: ^2.2.0
  multi_dropdown: ^2.1.4
  flutter_colorpicker: ^1.0.3
  flutter_local_notifications: ^17.0.1
  flutter_datetime_picker: ^1.5.1
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.1
  sentry_flutter: ^7.18.0
  riverpod_generator: ^2.4.0
  flutter_rating_bar: ^4.0.1
  hive:
  hive_flutter:
  cached_network_image:
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.30.0
  firebase_crashlytics: ^3.5.2
  firebase_analytics: ^10.10.2
  connectivity_plus: ^6.0.3
  timezone: ^0.9.2
  permission_handler: ^11.3.1
  firebase_auth: ^4.19.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-icon/logo.png"
  remove_alpha_ios: true

analyzer:
  errors:
    invalid_annotation_target: ignore

flutter:
  uses-material-design: true
  assets:
      - assets/icons/
      - assets/images/bg.jpg
      - assets/images/sticker.png
      - assets/images/buildings/AU.jpg
      - assets/images/buildings/B.jpg
      - assets/images/buildings/C.jpg
      - assets/images/buildings/LL.jpg
      - assets/images/buildings/ML.jpg
      - assets/images/buildings/O.jpg
      - assets/images/buildings/R.jpg
      - assets/images/buildings/RGD.jpg
      - assets/images/buildings/SD.jpg
      - assets/images/buildings/W.jpg
      - assets/images/profile_pics/user_1.png
      - assets/images/profile_pics/user_2.png
      - assets/images/profile_pics/user_3.png
      - assets/images/profile_pics/user_4.png
      - assets/images/profile_pics/user_5.png
      - assets/images/profile_pics/user_6.png
      - assets/images/profile_pics/user_7.png
      - assets/images/profile_pics/user_8.png
      - assets/images/profile_pics/user_9.png
      - assets/images/profile_pics/user_10.png
      - assets/images/profile_pics/user_11.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf